### ISSUE TITLE
Retrieving CountDecimate last value when does not correspond to specified interval

### ISSUE THREAD

**Issue by qbetti** [liflab/beepbeep-3#33]
Let's say we have this code : 
```
QueueSource source = new QueueSource();
source.loop(false);
for(int i = 0; i < 500; i++) {
	source.addEvent(Integer.toString(i));
}

// Initializing Pump and FileWriter

Connector.connect(source, new CountDecimate(501), pump, writer);
pump.run();
```
Since the `CountDecimate` interval is superior to the number of events in the `source` (but it's also true when the number of events is not a strict multiple of the interval), it will only output the first event (or the event of the last interval).
It would be nice to have an option (or another class) to specify if we want the `CountDecimate` to output the LAST event (i.e. when there is nothing more to pull) even if it does not correspond to the interval.

**Comment by sylvainhalle** [comment]
Oops, thought it was done

**Comment by qbetti** [comment]
Um, I think it should work. And for `TimeDecimate` too.
For both of these classes, there is a constructor `public CountDecimate(int interval, boolean should_process_last_inputs)` or `public TimeDecimate(long interval, boolean should_process_last_inputs)` that allows to specify if you want the processor to output the last event even though it does not correspond to your decimation interval. 

Let me know if there is any problem as I'm not sure I have actually pushed the tests for these features.

**Comment by sylvainhalle** [comment]
It works! Closing again. ;-)
