### ISSUE TITLE
FileWriter throws NullPointerException in append mode

### ISSUE THREAD

**Issue by qbetti** [liflab/beepbeep-3#34]
Following code throws `NullPointerException` : 
```
QueueSource source = new QueueSource();
source.loop(false);
for(int i = 0; i < 42; i++) {
    source.addEvent(Integer.toString(i));
}

Pump pump = new Pump();
FileWriter writer = new FileWriter(new File("./Example/test.txt"), true);

Connector.connect(source, pump, writer);

pump.run();
```

But works correctly when append mode is disabled : 
```FileWriter writer = new FileWriter(new File("./Example/test.txt"), false);```

The problem seems to come from `FileWriter#append` where `m_outStream` is not defined, whereas `m_outStream` is well defined in `FileWriter#overwrite` which is only called when `m_append == false`.

**Comment by sylvainhalle** [comment]
Replaced by the `WriteOutputStream` processor
