### ISSUE TITLE
Constructor Maps class

### ISSUE THREAD

**Issue by Hellois-Barbosa** [liflab/beepbeep-3#45]
I find an issue in Maps.Get class an inner class of Maps. Indeed when I create a new Object Maps.Get I see the following error:
`The constructor Maps.Get(String) is not visible`
In fact, Maps.Get constructor is **protected**.

![image](https://user-images.githubusercontent.com/50337943/57305753-d5e4b980-70e1-11e9-8eda-03a54580975e.png)

**Comment by sylvainhalle** [comment]
Duplicate of #46
