### ISSUE TITLE
Restrictive constructor

### ISSUE THREAD

**Issue by Hellois-Barbosa** [liflab/beepbeep-3#48]
We can use a function `Function f = new **Bags.FilterElements();**`

However htis function take only simple function like parameter: `UnaryFunction<?, Boolean>` but cannot allow to insert for example other function with arity 1:1 which is not extends of `UnaryFunction` like `FunctionTree` with only one `StreamVariable`.

You should add the following precondition in JML: `/*@ requires f.getInputArity() == 1 @*/`

**Comment by sylvainhalle** [comment]
In other words, the constructor for `FilterElements` should accept a `Function` instead of a `UnaryFunction`.
