### ISSUE TITLE
page guide for Eclipse build not found

### ISSUE THREAD

**Issue by jalvesnicacio** [liflab/beepbeep-3#50]
The page https://liflab.github.io/beepbeep-3/guide/building-eclipse.html is not found

**Comment by sylvainhalle** [comment]
This sentence should simply be deleted. There is no such guide.

**Comment by jalvesnicacio** [comment]
I created this simple manual:
[https://docs.google.com/document/d/1o8dPn-1eEWmOzwdeAr_7eqa88iKrYmL63-rGtkloU6k/edit?usp=sharing](https://docs.google.com/document/d/1o8dPn-1eEWmOzwdeAr_7eqa88iKrYmL63-rGtkloU6k/edit?usp=sharing)

**Comment by sylvainhalle** [comment]
Indeed! I'll fix this in the Readme.

**Comment by sylvainhalle** [comment]
Closed by caf84.
