### ISSUE TITLE
Iterator.next should throw NoSuchElementException

### ISSUE THREAD

**Issue by mernst** [liflab/beepbeep-3#53]
The [`Iterator.next()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Iterator.html#next()) method is specified to throw `NoSuchElementException` if the iteration has no more elements.  It is not supposed to return null in that situation.

`Pullable.next` is a subclass of `Iterator` but violates its specification:

```java
  /**
   * Synonym of {@link #pull()}.
   * 
   * @return An event, or <code>null</code> if none could be retrieved
   */
  @Override
  public @Nullable Object next();
```

It would be helpful to clients if BeepBeep adheres to the iterator specification.
Or, is there a reason it does not do so?

**Comment by sylvainhalle** [comment]
I must confess I was not aware of this element of the specification. The behavior of `next` could probably be changed to adhere to it, but I'll first have to double-check it does not break anything within the library.
