### ISSUE TITLE
Why does `Pushable.pushFast()` return `Future<Pushable>`?

### ISSUE THREAD

**Issue by mernst** [liflab/beepbeep-3#61]
`Pushable.pushFast()` returns a `Future<Pushable>`.
When the resulting `Future` is done, the the push has occurred.

Given the return type of `Pushable.pushFast()`, I expected that the object in the future would be the receiver (the `this` object).  I tried code like this:

```java
Pushable p = ...;
...
Future<Pushable> f = p.pushFast(o);
...

// later, maybe in a different method:
p = f.get();
... use p ...
```

However, that code fails because the future `f` always contains a `PushNotSupported`, which is documented as "This object can be returned by processors to signal that they cannot be pushed."

The code works if I ignore the return value of the call to `get`, by changing `p = f.get()` to `f.get()`.  A downside of that change is that I need to pass both the `Pushable` and the `Future` around rather than just the `Future`.

Question: Is it intended that the user should never use the result of the `get()` method on a value of type `Future<Pushable>`?

If not:
 * How should I use the result of `get()`?

If so:
 * Could you please document this fact?
 * I have a followup question.  Why is the type `Future<Pushable>`?  If the value will never be used, then I think `Future<Void>` would convey the intent more clearly.

Thanks in advance for your explanation!

**Comment by sylvainhalle** [comment]
I must confess this was one of my first attempts at dealing with concurrency and threads. It is very possible I didn't follow the standard practice for using these objects.

The default behavior (implemented in `SynchronousProcessor.InputPushable.pushFast()`) is to *not* allow multiple non-blocking calls to `push`; this is done by returning a `Future` object whose internal `Pushable` does not allow any further calls to `push`. This way, the default behavior of  `pushFast` is to be a blocking call as is `push`.

If a particular descendant of `SynchronousProcessor` wants to behave differently, it must override this behavior and return a `Future` whose `Pushable` does allow further calls to `push`. You won't see this in this repository; the only processors that override  `pushFast` are in a palette called [Concurrency](https://github.com/liflab/beepbeep-3-palettes/tree/master/Concurrency).

Again, I am not sure this was the cleanest way of achieving this result, but I hope this makes things clearer.

**Comment by sylvainhalle** [comment]
This issue is moot since d3546d3e3733fc47e64ab19c4a6c8f33c4ef2f2b
